version: '3'

services:

  www:
    hostname: www
    build: './cloud/public/www'
    restart: always
    volumes:
      - './cloud/public/www/html:/usr/share/nginx/html'
    ports:
      - '80:80'

  panel:
    hostname: panel
    build: './cloud/public/panel'
    restart: always
    volumes:
      - './cloud/public/panel/html:/usr/share/nginx/html/panel'

  files:
    hostname: files
    build: './cloud/public/files'
    restart: always
    volumes:
      - './data/upload:/usr/share/nginx/html/files'

  api_upload:
    hostname: api_upload
    build: './cloud/api/upload'
    restart: always
    volumes:
      - './cloud/api/upload:/go/src'
      - './cloud/api/commons:/jornal/commons'
      - './data:/jornal/data'

  api_users_login:
    hostname: api_users_login
    build: './cloud/api/users-login'
    restart: always
    volumes:
      - './cloud/api/users-login:/jornal/app'
      - './cloud/api/commons:/jornal/commons'
      - './data:/jornal/data'

  api_users_register:
    hostname: api_users_register
    build: './cloud/api/users-register'
    restart: always
    volumes:
      - './cloud/api/users-register:/jornal/app'
      - './cloud/api/commons:/jornal/commons'
      - './data:/jornal/data'
