version: '3'

services:

  www:
    hostname: www
    build: './src/public/www'
    restart: always
    volumes:
      - './src/public/www/html:/usr/share/nginx/html'
      - './data/public:/usr/share/nginx/html/jornal'
      - './data/upload:/usr/share/nginx/html/files'
    ports:
      - '80:80'

  panel:
    hostname: panel
    build: './src/public/panel'
    restart: always
    volumes:
      - './src/public/panel/html:/usr/share/nginx/html/panel'

  api_upload:
    hostname: api_upload
    build: './src/api/upload'
    restart: always
    volumes:
      - './src/api/upload:/go/src'
      - './src/commons:/jornal/commons'
      - './data:/jornal/data'

  api_users_login:
    hostname: api_users_login
    build: './src/api/users-login'
    restart: always
    volumes:
      - './src/api/users-login:/jornal/app'
      - './src/commons:/jornal/commons'
      - './data:/jornal/data'

  api_users_register:
    hostname: api_users_register
    build: './src/api/users-register'
    restart: always
    volumes:
      - './src/api/users-register:/jornal/app'
      - './src/commons:/jornal/commons'
      - './data:/jornal/data'

  api_news_create:
    hostname: api_news_create
    build: './src/api/news-create'
    restart: always
    volumes:
      - './src/api/news-create:/jornal/app'
      - './src/commons:/jornal/commons'
      - './data:/jornal/data'

  api_news_list:
    hostname: api_news_list
    build: './src/api/news-list'
    restart: always
    volumes:
      - './src/api/news-list:/jornal/app'
      - './src/commons:/jornal/commons'
      - './data:/jornal/data'
